### ISSUE TITLE
Vox Pupuli migration

### ISSUE THREAD

**Issue by b4ldr** [voxpupuli/puppet-dnsquery#115]
Hello @dalen,

Thanks for the great module however looking at the issues, open PR's and supported versions  it would seem that this module is possibly now abandoned, suspect you have moved on to more fun/different projects.  If that is the case i wonder if you would be willing to migrate the repo to voxpupil, id be happy to [do the work for this](https://voxpupuli.org/docs/migrate_module/) and maintain the module going forward but would need access to the repo to transfer it

Thanks

**Comment by dalen** [comment]
Sure, invited you as collaborator on it.

I have a couple of other modules that could be moved to voxpopuli as well.

**Comment by b4ldr** [comment]
great thanks ill pick this up once i have clocked off for the day

**Comment by bastelfreak** [comment]
hey @dalen, long time no see! I added you to our migrationa github group at Vox Pupuli. You should be able to migrate puppet-dnsquery.

**Comment by b4ldr** [comment]
@dalen just as an update i didn't have the required permissions to transfer the repo, i gusse you need to be the owner.  Anyway as said if you can transfer the repo to voxpupuli i can pick up the rest of the task from there thanks

**Comment by dalen** [comment]
it is migrated to voxpopuli org now. Thanks for taking over the maintenance of it. If there's any of my other old modules still of interest feel free to take care of them as well.

I guess puppetdbquery was the most popular, but I imagine everyone has moved over to the build in query functions in puppetdb by now, even if they are a bit more verbose to write.

**Comment by b4ldr** [comment]
thanks @dalen i was on vacation last week ill pick this up tomorrow :)
