### ISSUE TITLE
Anyone know how to use this in a template?

### ISSUE THREAD

**Issue by treveradams** [voxpupuli/puppet-dnsquery#12]
I do have some puppet experience, but I am having difficulty using this function from a template. Does anyone have a suggestion on how to do this?

**Comment by witchbutter** [comment]
It's functionally the same to pass a variable to your template. In the pp file:

```
$someip = dns_a('somename')[0]

file{ 'afilefromtemplate:
  ...
  content => template("${module_name}/somemodule/someconffile.erb"),
  ...
}
```

then in your erb:

`<%= @someip %>`
