### ISSUE TITLE
tarball for v3.0.0 on the Forge includes vendored Ruby

### ISSUE THREAD

**Issue by walkamongus** [voxpupuli/puppet-dnsquery#13]
For some reason the v3.0.0 tarball on the Forge includes a vendored Ruby distribution. The uncompressed size of the module is ~48M and the vendor directory is ~47M removing this would save space as well as cut down on the files needing to be scanned by puppetserver during startup.

**Comment by Andor** [comment]
Same.

**Comment by Ultimation** [comment]
Yup. Had to point Puppetfile at this git directly. Not a huge problem but caused our build to initially fail.

**Comment by tskirvin** [comment]
Same problem here.

**Comment by b4ldr** [comment]
Im closing this, once the repo has been cleaned up we will do a new release under the voxpupli namespace
