### ISSUE TITLE
dns_ptr is broken on Ubuntu 18.04

### ISSUE THREAD

**Issue by morremeyer** [voxpupuli/puppet-dnsquery#41]
On a newly installed Ubuntu Server 18.04.1,

`dns_ptr` looks broken:

```
% cat test.pp

$ptr_me = dns_ptr($ipaddress)
$ptr_cf = dns_ptr('1.1.1.1')

notify { "PTR me: ${ptr_me}": }
notify { "PTR cloudflare: ${ptr_cf}": }
% /opt/puppetlabs/bin/puppet apply --modulepath /home/morre/puppet/modules/ /home/morre/test.pp
Notice: Compiled catalog for v22018096252574082.luckysrv.de in environment production in 0.06 seconds
Notice: PTR me: []
Notice: /Stage[main]/Main/Notify[PTR me: []]/message: defined 'message' as 'PTR me: []'
Notice: PTR cloudflare: []
Notice: /Stage[main]/Main/Notify[PTR cloudflare: []]/message: defined 'message' as 'PTR cloudflare: []'
Notice: Applied catalog in 0.02 seconds
```

All my debugging attempts have run into walls.

I’m running:

* Ubuntu Server 18.04.1
* Puppet 5.5.8
* puppet-dnsquery 3.0.0

Please let me know if I can help solving the issue in any way.

**Comment by kindlehl** [comment]
ptr records are formatted differently. You have to reverse the octets and add '.in-add.arpa'. So if your IP is 10.0.70.4 then the PTR to look for is 4.70.0.10.in-addr.arpa.
