### ISSUE TITLE
dns_cname: stops puppet with an error if record is not resolvable

### ISSUE THREAD

**Issue by ivoruetsche** [voxpupuli/puppet-dnsquery#57]
Hi

When I work with dns_cname, the puppet will stop with an error:

Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Evaluation Error: Error while evaluating a Function Call, DNS result has no information for myrecord.mydomain.com

With dns_a, dns_srv etc. works fine.

Ivo

**Comment by martijndegouw** [comment]
You can add a lambda to the function call to return a default value if the resolution fails.
class test_dns_default {

  $pcb_ip = dns_cname('fakesubdomain.puppetcookbook.com') || { 'nowhere' }

  notify { "Puppetcookbook is at ${pcb_ip}": }

}

Notice: Puppetcookbook is at 127.0.0.1

See the [Puppet cookbook](https://www.puppetcookbook.com/posts/dns-lookups-in-puppet.html)

**Comment by b4ldr** [comment]
seems this was answered please reopen if there are still questions
