### ISSUE TITLE
Installs 53M vendor directory from puppetforge 

### ISSUE THREAD

**Issue by madduck** [voxpupuli/puppet-dnsquery#84]
If I install from puppetforge, the download includes a 53M `vendor` directory with a full copy of Puppet 4.4. Removing that directory does not affect operation. I suppose therefore it does not need to be installed.

**Comment by tskirvin** [comment]
I've been using a forked version of this module for the last few years because of this bug.  Can we get it fixed?  Should be a simple fix.

**Comment by b4ldr** [comment]
Im closing this, once the repo has been cleaned up we will do a new release under the voxpupli namespace (also duplicates #13)
